openapi: 3.0.1
info:
  title: Site Repository API
  description: API that manages site entities.
  version: 1.0.0
servers:
- url: http://localhost/api/v1
tags:
- name: site
  description: Site management
paths:
  /site:
    put:
      tags:
      - site
      summary: Update an existing site
      requestBody:
        description: Site object that needs to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Site'
        required: true
      responses:
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Site is not found
          content: {}
        "422":
          description: Validation exception
          content: {}
      x-codegen-request-body-name: body
    post:
      tags:
      - site
      summary: Add a new site
      requestBody:
        description: Site object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Site'
        required: true
      responses:
        "400":
          description: Invalid input
          content: {}
        "422":
          description: Validation exception
          content: {}
      x-codegen-request-body-name: body
  /site/queryByUser:
    get:
      tags:
      - site
      summary: Queries sites by user
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Site'
        "400":
          description: Invalid status value
          content: {}
  /site/{siteId}:
    get:
      tags:
      - site
      summary: Gets site by ID
      description: Returns a site
      parameters:
      - name: siteId
        in: path
        description: ID of site to return
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Site'
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Site not found
          content: {}
    delete:
      tags:
      - site
      summary: Deletes a site
      parameters:
      - name: siteId
        in: path
        description: ID of site to delete
        required: true
        schema:
          type: integer
      responses:
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Site not found
          content: {}
components:
  schemas:
    Site:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
x-original-swagger-version: "2.0"

