@startuml Microservices

title Warmhouse Microservices Container Diagram

!include <C4/C4_Component>

Person(User, "User", "A user of the warmhouse system")
Person(Admin, "Administrator", "An administrator managing the system")

System_Boundary(WarmhouseSystem, "Warmhouse System", "System managing, issuing commands to and collecting data from temperature sensors") {
    Container(WebUI, "Web UI", "Microfrontend", "End-user interface Web UI fronend")
    Container(MobileUI, "Mobile UI", "Application", "End-user interface mobile app")
    Container(UIAPIGateway, "UI API Gateway", "Service", "API gateway for both end-user UI modules")
    Container(WebAdminUI, "Web Admin UI", "Service", "Admin user interface Web UI fronend")
    Container(AdminUIAPIGateway, "Admin UI API Gateway", "Service", "API gateway for both admin UI")
    Container(DeviceRepositoryService, "Device Repository Service", "Service", "Holds device entities, performs CRUD operations")
    ContainerDb(DeviceRepositoryDatabase, "Device Database", "Service", "Holds static device data")
    Container(DeviceConnectorService, "Device Connector Service", "Service", "Talks to devices via external API, asynchronousyl processes commands to be passed to the devices, publishes device statuses (command results) and telemetry values")
    Container(TelemetryService, "Telemetry Service", "Service", "Collects, aggregates and caches telemetry data to provide it to the other services with low latency")
    Container(SiteRepositoryService, "Site Repository Service", "Service", "Holds site entities, performs CRUD operations")
    ContainerDb(SiteRepositoryDatabase, "Site Database", "Service", "Holds site data")
    Container(UserRepositoryService, "User Repository Service", "Service", "Holds user entities, performs CRUD operations")
    ContainerDb(UserRepositoryDatabase, "User Database", "Service", "Holds user data")
    ContainerDb(MessageQueuee, "Message Queue", "Service", "Passes telemetry, commands and their results among services")
}

System_Ext(DeviceAPI, "Device API", "External API for temperature sensors")

Rel(User, WebUI, "Uses the system")
Rel(User, MobileUI, "Manages the system")
Rel(Admin, WebAdminUI, "Manages the system")
Rel(WebUI, UIAPIGateway, "Calls")
Rel(MobileUI, UIAPIGateway, "Calls")
Rel(UIAPIGateway, DeviceRepositoryService, "Calls")
Rel(UIAPIGateway, TelemetryService, "Calls")
Rel(DeviceRepositoryService, DeviceRepositoryDatabase, "Uses")
Rel(UIAPIGateway, SiteRepositoryService, "Calls")
Rel(SiteRepositoryService, SiteRepositoryDatabase, "Uses")
Rel(DeviceRepositoryService, SiteRepositoryService, "Calls")
BiRel(DeviceRepositoryService, DeviceConnectorService, "Calls")
Rel(DeviceRepositoryService, UserRepositoryService, "Calls")
Rel(DeviceConnectorService, DeviceAPI, "Calls")
Rel(UserRepositoryService, UserRepositoryDatabase, "Uses")
Rel(WebAdminUI, AdminUIAPIGateway, "Calls")
Rel(AdminUIAPIGateway, DeviceRepositoryService, "Calls")
Rel(AdminUIAPIGateway, UserRepositoryService, "Calls")
Rel(AdminUIAPIGateway, SiteRepositoryService, "Calls")
Rel(MessageQueuee, TelemetryService, "Consumes telemetry")
BiRel(DeviceConnectorService, MessageQueuee, "Publishes telemetry and command results, consumes commands")

@enduml