@startuml Microservices

title Warmhouse Microservices Container Diagram

!include <C4/C4_Component>

Person(User, "User", "A user of the warmhouse system")
Person(Admin, "Administrator", "An administrator managing the system")
'System(WarmhouseSystem, "Warmhouse System", "System managing, issuing commands to and collecting data from temperature sensors")

System_Boundary(WarmhouseSystem, "Warmhouse System", "System managing, issuing commands to and collecting data from temperature sensors") {
    Container(WebUI, "Web UI Microfrontend", "Service", "Handles user interactions and system management")
    Container(MobileUI, "Mobile UI", "Service", "Handles user interactions and system management")
    Container(UIAPIGateway, "UI API Gateway", "Service", "Handles user interactions and system management")
    Container(WebAdminUI, "Web Admin UI", "Service", "Handles user interactions and system management")
    Container(AdminUIAPIGateway, "Admin UI API Gateway", "Service", "Handles user interactions and system management")
    Container(DeviceRepositoryService, "Device Repository Service", "Service", "Handles user interactions and system management")
    ContainerDb(DeviceRepositoryDatabase, "Device Database", "Service", "Handles user interactions and system management")
    Container(DeviceConnectorService, "Device Connector Service", "Service", "Handles user interactions and system management")
    Container(SiteRepositoryService, "Site Repository Service", "Service", "Handles user interactions and system management")
    ContainerDb(SiteRepositoryDatabase, "Site Database", "Service", "Handles user interactions and system management")
    Container(UserRepositoryService, "User Repository Service", "Service", "Handles user interactions and system management")
    ContainerDb(UserRepositoryDatabase, "User Database", "Service", "Handles user interactions and system management")
}

System_Ext(DeviceAPI, "Device API", "External API for temperature sensors")

Rel(User, WebUI, "Uses the system")
Rel(User, MobileUI, "Manages the system")
Rel(Admin, WebAdminUI, "Manages the system")
Rel(WebUI, UIAPIGateway, "Calls")
Rel(MobileUI, UIAPIGateway, "Calls")
Rel(UIAPIGateway, DeviceRepositoryService, "Calls")
Rel(DeviceRepositoryService, DeviceRepositoryDatabase, "Uses")
Rel(UIAPIGateway, SiteRepositoryService, "Calls")
Rel(SiteRepositoryService, SiteRepositoryDatabase, "Uses")
Rel(DeviceRepositoryService, SiteRepositoryService, "Calls")
BiRel(DeviceRepositoryService, DeviceConnectorService, "Calls")
Rel(DeviceRepositoryService, UserRepositoryService, "Calls")
Rel(DeviceConnectorService, DeviceAPI, "Calls")
Rel(UserRepositoryService, UserRepositoryDatabase, "Uses")
Rel(WebAdminUI, AdminUIAPIGateway, "Calls")
Rel(AdminUIAPIGateway, DeviceRepositoryService, "Calls")
Rel(AdminUIAPIGateway, UserRepositoryService, "Calls")
Rel(AdminUIAPIGateway, SiteRepositoryService, "Calls")



@enduml